### ISSUE TITLE
File Manager sorting

### ISSUE THREAD

**Issue by MorningSleeper** [authentic-theme/authentic-theme#1345] opened 2019-05-15 22:57 UTC
Using Authentic Theme 19.33 on Ubuntu 18.04.2, trying to sort files in File Manager, click on Modified column header but some with older modified date are surrounded by ones with a newer file date, see screenshot. Also for those that are on the same date, say 5/15/19, they are not all in order by time. I clicked refresh, cleared cache in Authentic Theme and changed default sort order back and forth.

![image](https://user-images.githubusercontent.com/8920632/57815067-c04b4180-772a-11e9-95bd-e9932634a88f.png)

If the info on hover helps ...

![test](https://user-images.githubusercontent.com/8920632/57816214-508b8580-772f-11e9-88dc-0ff1261869f4.gif)

**Comment by rostovtsev** [comment] 2019-05-16 09:57
Indeed. It's fixed with the latest commit.

Thanks for reporting. :smiley:

**Closed by rostovtsev** 2019-05-16 09:57 UTC

**Comment by MorningSleeper** [comment] 2019-06-01 20:58
One follow up question, lets say I have it set to show 30 items per page. When I click the modified header to resort the files in descending order, is it supposed to look at all files in the current directory (over 500) to determine the order and what files to display on that first page or only those 30 files displayed on the current page before I clicked the header. It does sort those on current page correctly now but if I go to next page it shows files with modified dates that are newer than the ones on first page. I was hoping to be able to click the modified header to view the most recent files in the directory regardless of what page they are on.

**Comment by rostovtsev** [comment] 2019-06-01 21:53
Yes, correct.

When server pagination is active (for directories with many files), the sorting only applied to the current page.

It's not easy to implement it by combining all modes properly. Besides, sorting for 1m+ files might take considerable amount of time. It's better to use search and then do something with results.

I might go for it and also add sorting when server pagination is active but it's gonna take considerable amount of efforts.

As workaround, if there are just < 1000 files, you can make it all displayed without server pagination (see File Manager configuration).

**Comment by MorningSleeper** [comment] 2019-06-01 22:00
Ok, thanks for info, I see that "Default number of items in directory to initiate server pagination" setting, looks like it works for 2000 or less. I have 1800 files in that directory so setting it to 2000 solves the issue for me for the moment. Since I expect the number of files to grow in that directory, nothing like millions but a couple thousand more perhaps, any chance a higher number choice can be added in that drop down menu or is 2000 the max?

**Comment by rostovtsev** [comment] 2019-06-01 22:13
It could but the problem is, that it would be very slow and most probably would crash your browser.

**Comment by MorningSleeper** [comment] 2019-06-01 22:29
Ok, well if you can add a slightly higher option(s) for that setting in a future version, that would be helpful. For your reference, with 1868 files it takes 13 seconds to enter the directory (which I do not mind) and then clicking Modified header it instantaneously sorts all of them which is exactly what I wanted, thanks.

**Comment by rostovtsev** [comment] 2019-06-04 15:43
Added it.
