### ISSUE TITLE
Favorites open error (Error - Perl execution failed)

### ISSUE THREAD

**Issue by sprinter11** [authentic-theme/authentic-theme#1377] opened 2019-07-02 16:59 UTC
When I try to open favorites, I get this
![Снимок экрана от 2019-07-02 19-46-25](https://user-images.githubusercontent.com/12623959/60530905-7b8f6000-9d02-11e9-9ef0-dafdc3d3cde3.png)
Language is RU.UTF-8 and favorites-root.json contains titles with russian symbols (utf8). Also dashboard is not working.

**Comment by rostovtsev** [comment] 2019-07-02 21:09
HI,

It seems that you saved _**favorites-root.json**_ file not in _UTF-8_ encoding but in some other, for example in _Cyrillic Windows_ or in _Cyrillic ISO 8859-5_ or some other.

Convert and save it using only in _UTF-8_, and make sure that _**favorites-root.json**_ file doesn't contain any rubbish characters. It should look something like this:


```JSON
{"favorites":[
    {
        "link": "/webmin/edit_themes.cgi",
        "title": "Webmin/Настройка Webmin: Темы Webmin",
        "icon": "webmin"
    },
    {
        "link": "/acl/",
        "title": "Webmin/Пользователи Webmin",
        "icon": "webmin"
    },
    {
        "link": "/webmin/",
        "title": "Webmin/Настройка Webmin",
        "icon": "webmin"
    },
    {
        "link": "/webmin/edit_startpage.cgi",
        "title": "Webmin/Настройка Webmin: Главное меню",
        "icon": "webmin"
    }
]}
```

The easiest way is just to delete the file and re-create favorites again, unless you have many saved.

After editing the file force reload the browser's page.

**Comment by sprinter11** [comment] 2019-07-03 09:27
Hello, favorites-root.json file is in UTF-8 and was created by webmin itself
![Снимок экрана от 2019-07-03 12-13-31](https://user-images.githubusercontent.com/12623959/60579664-3e6fb000-9d8c-11e9-999f-d3ac6b408a74.png)

I just did a fresh install of webmin. Then I changed language to RU.UTF-8 and added to favorites one point. Then reloaded page and got this result.

**Comment by rostovtsev** [comment] 2019-07-03 10:57
What browser did you use?

**Comment by rostovtsev** [comment] 2019-07-03 11:19
Besides, what theme and Webmin versions do you have installed?

**Comment by rostovtsev** [comment] 2019-07-03 11:48
One more, provide the screenshot for _Webmin/Webmin Configuration/Language and Locale_.

**Comment by sprinter11** [comment] 2019-07-03 13:35
I use Chrome 75.0.3770.100 and Firefox 67.0.4. Both have the same behavior.
Webmin 1.910, Authentic theme version 19.35.
![Снимок экрана от 2019-07-03 16-31-01](https://user-images.githubusercontent.com/12623959/60595818-6bce5500-9db0-11e9-9a79-30678527e102.png)

**Comment by rostovtsev** [comment] 2019-07-03 15:57
I tried to reproduce it but I couldn't. I have exactly the same settings.

If you delete _favorites-root.json_ and reload the page, then everything works fine? What if you add to favorites once again, the error is not repeated, and favorites just work, correct?

What is your OS where you're running Webmin?

**Comment by sprinter11** [comment] 2019-07-04 09:52
No, recreating favorites-root.json is not a solution. 
Looks like a problem in the Perl version. If Webmin is installed on Ubuntu 18.04 with Perl 5.26.1 everything works fine. On Scientific Linux 6.7 with Perl 5.10.1 there is a problem I wrote before.

**Comment by rostovtsev** [comment] 2019-07-04 09:55
I will have to test more on earlier versions of Perl, as version 5.10 yet officially supported by us.

**Comment by rostovtsev** [comment] 2019-07-04 10:28
Perl 5.10.1 was release over 12 years ago, I am just curious before trying, are you sure that it's not a Perl bug or missing feature at that moment?

https://en.wikipedia.org/wiki/Perl_5_version_history

**Comment by rostovtsev** [comment] 2019-07-04 13:03
Okay, I have install Scientific Linux 6.7 with Perl 5.10.1.

It just works:

![image](https://user-images.githubusercontent.com/4426533/60668578-fb3d3c00-9e74-11e9-82b2-316be200ff51.png)


This is what I get after page reload:

![image](https://user-images.githubusercontent.com/4426533/60668603-08f2c180-9e75-11e9-9c23-fe38541a8466.png)

Please provide more details on how to reproduce this issue. I will close it for now.

**Closed by rostovtsev** 2019-07-04 13:03 UTC

**Comment by sprinter11** [comment] 2019-07-04 14:47
I got a solution. It looks very wierd, but as it is. In the **sub print_favorites** function from the **authentic-lib.pm** file inside the **foreach my $favorite (@{ $fc->{'favorites'} })** cycle I changed **$favorite->{"title"}** to **$converter->convert($favorite->{"title"})**. And put before the cycle
**use Text::Iconv;
my $converter = Text::Iconv->new("UTF-8", "UTF-8 //TRANSLIT");**

![Снимок экрана от 2019-07-04 17-16-26](https://user-images.githubusercontent.com/12623959/60673024-828fad00-9e7f-11e9-85b7-5066e5baed6c.png)

Text::Iconv package required.
The same trick with the **settings-favorites_save.cgi** file does not work.

**Comment by sprinter11** [comment] 2019-07-04 14:56
My assumption that this problem is because of the Perl version is wrong. On Scientific Linux 6.7 with Perl 5.30 the problem is still there.

**Comment by rostovtsev** [comment] 2019-07-04 16:38
I gave it more tries - it just works for me on Scientific Linux 6.7 with stock Perl 5.10.1.

**Comment by sprinter11** [comment] 2019-07-05 15:57
It seems to be a Perl or Webmin bug, I don't know exactly. I think it is wrong autodetection of utf8.
I changed **return JSON::PP->new->utf8->decode($json_text);** to **return JSON::PP->new->utf8(0)->decode($json_text);** in the **sub convert_from_json** function from the **web-lib-funcs.pl** file. Then Webmin on Scientific Linux 6.7 started working properly. Webmin on Ubuntu 18.04 shows this
![Снимок экрана от 2019-07-05 18-16-21](https://user-images.githubusercontent.com/12623959/60731834-3a40bf80-9f51-11e9-9b65-26a7250f11b6.png)
