### ISSUE TITLE
Issue with file upload modal window

### ISSUE THREAD

**Issue by pixel-paul** [authentic-theme/authentic-theme#1483] opened 2020-07-15 10:15 UTC
This is a minor issue on Firefox. It works as expected on Chrome.

Authentic theme version: 19.52 (but prior versions too)
Firefox 79 (but prior version too)

If you select a radio button and then click the file upload icon, nothing happens.

![Screenshot_2020-07-15](https://user-images.githubusercontent.com/389303/87533213-2c596a80-c68c-11ea-8fa1-6266442c9fcb.png)

If you do not select the radio button and click the file upload button, the pop up window appears as expected.

So if there are more than 2 file uploads (such as with an SSL cert), you're stuck!

Thanks,

Paul

**Comment by iliarostovtsev** [comment] 2020-07-15 14:05
Hi,

I suppose you're on **mysql/exec_form.cgi** page and using **Execute SQL**?

I don't understand what the problem is? It works for me just fine in latest Firefox on Linux. What exactly doesn't work?

**Comment by pixel-paul** [comment] 2020-07-15 16:31
The bug is not limited to a specific page, it is on all forms where there is a file upload element.

I wonder if this is limited to MacOSX, as it is not working in either Firefox  78.0.2 or 79b4. However, it works as expected on Firefox/Win10 

**Expected result:** When you click on the paperclip icon, a file brower window pops up. 

**Actual result:** If any radio button is selected _first_, clicking on the paperclip does nothing.

Here is a video: https://youtu.be/8OTusUwTtK0

**Comment by iliarostovtsev** [comment] 2020-07-15 18:12
Oh, I see an issue here.

Thank you very much. I will take a closer look a bit later. I will update it when it's fixed.

**Comment by iliarostovtsev** [comment] 2020-07-15 18:17
Yeah, I see why it's happening. Unbeforeunload status prevents a click on this button. As a work-around, if you need to do some work, just open a console and run `set_onbeforeunload_status(0)` before clicking the paperclip button.

I will fix it after dinner break.

**Comment by iliarostovtsev** [comment] 2020-07-19 17:30
It's fixed on the latest commit. We will release minor Webmin version containing the theme update really soon!

Thanks for the heads up!

**Closed by iliarostovtsev** 2020-07-19 17:30 UTC
