### ISSUE TITLE
right menu not acting on the good website

### ISSUE THREAD

**Issue by aqueos** [authentic-theme/authentic-theme#1409] opened 2019-10-04 14:30 UTC
hi,

  I encounter an issue on authentic theme.

 If i go to the page that list the virtual domains (https://xxxxxxxxxx:10000/virtual-server/index.cgi) then, in the 'domain name' colum i select a domain.

( that for exemple select https://xxxxxxxxxx:10000/virtual-server/edit_domain.cgi?dom=1570185770174112)

then the left  frame (menu frame)  do NOT change to the domain selected but stay on the one it was before. 

This can lead to deletion or changes to the wrong website.

Authentic theme version | 19.39-2
on debian 9

Version de Webmin | 1.930
Version Virtualmin | 6.07

Firefox 69.0.1 (64 bits) on ubuntu 18.04

best regards,
Ghislain.

**Comment by rostovtsev** [comment] 2019-10-04 21:55
Hi, Ghislain.

It just works for me? I tried it in Chrome and Firefox - it just works as expected. Could you provide video-screencast, please?

![Peek 2019-10-05 00-54](https://user-images.githubusercontent.com/4426533/66242672-b8f0f880-e70a-11e9-8263-6b253f9c0bf0.gif)

**Comment by aqueos** [comment] 2019-10-05 09:17
just tested on chrome and opera for the same result.

regards,
Ghsilain.

**Comment by rostovtsev** [comment] 2019-10-05 10:05
Does it mean that it's not working the way it does on my video-screencast?

Are there any errors in the console? Did you try restarting Webmin and force-clearing browser's cache?

**Comment by rostovtsev** [comment] 2019-10-05 10:19
Okay, I see what you mean now. I could reproduce it, on GPL version of Virtualmin.

**Comment by rostovtsev** [comment] 2019-10-05 10:45
Okay, it's fixed now. Thanks for reporting.

**Closed by rostovtsev** 2019-10-05 10:45 UTC

**Comment by aqueos** [comment] 2019-10-07 04:42
thanks a lot for this quick reply and action, like allways !

Ghislain
