### ISSUE TITLE
Theme: Disabled website not showing in red anymore

### ISSUE THREAD

**Issue by giampio** [authentic-theme/authentic-theme#1516] opened 2021-02-17 16:37 UTC
Disabled websites were showing in red in the Virtualmin dropdown (in the left menu) list of websites, this does not seem to work anymore.

Webmin version: 1.962 
Virtualmin version: 6.14 
Authentic theme version: 19.62

**Comment by iliarostovtsev** [comment] 2021-02-17 18:40
Hi,

It still works for me.

Perhaps it depends on the mode - how many websites do you host approximately?

**Comment by giampio** [comment] 2021-02-18 11:33
Hi thank you
I have four servers with different websites (about twenty for server). 
Before update, sites disabled  appeared red in the list. Now only once selected it

![Senza-titolo](https://user-images.githubusercontent.com/7437607/108351227-8489b980-71e5-11eb-9c14-2201eb9665a3.jpg)

![Senza-titolo-a](https://user-images.githubusercontent.com/7437607/108351236-881d4080-71e5-11eb-9347-64a110428d07.jpg)

**Comment by iliarostovtsev** [comment] 2021-02-18 12:25
I see what you mean now. Confirmed.

**Comment by iliarostovtsev** [comment] 2021-02-23 20:44
This will be fixed in upcoming release. 


Thanks for reporting!

**Closed by iliarostovtsev** 2021-02-23 20:44 UTC
