### ISSUE TITLE
Strange date/time behavior

### ISSUE THREAD

**Issue by Sopor** [authentic-theme/authentic-theme#1427] opened 2019-11-19 13:36 UTC
### The format i use is `YYYY-MM-DD` and `LTS` but in the recent logins i can't see any seconds
![image](https://user-images.githubusercontent.com/5789283/69150262-a07d4780-0ad8-11ea-8349-5c5ec8710b3e.png)
### even if i use LTS
![image](https://user-images.githubusercontent.com/5789283/69150505-184b7200-0ad9-11ea-853d-d5094a39c5a9.png)

### When i hover over the short format it will show 19/11/2019
![image](https://user-images.githubusercontent.com/5789283/69150347-d1f61300-0ad8-11ea-9181-d915b95edfd6.png)

### but if i first set the cursor in the date format and now hover again it will now show 2019-11-19
![image](https://user-images.githubusercontent.com/5789283/69150454-fa7e0d00-0ad8-11ea-8727-ecbdf48f7309.png)

**Comment by rostovtsev** [comment] 2019-11-19 14:26
Duh, you're right!

What a great bug report, right on the eve of release!

Thanks a lot. :wink:  Fixed on the latest commit.

**Closed by rostovtsev** 2019-11-19 14:26 UTC

**Comment by Sopor** [comment] 2019-11-19 18:01
The tooltip showing output example is still having the same behavior. Is that not fixable?

**Comment by rostovtsev** [comment] 2019-11-19 18:31
It's fixed for Recent Logins, right?

Now tooltip for time, on configuration page doesn't show it right?

**Comment by rostovtsev** [comment] 2019-11-19 19:12
I think I know what you mean now.

**Comment by rostovtsev** [comment] 2019-11-19 19:20
Okay, you were trying to report two issues in one post with no evident emphasis?

The first issue boundary was `even if i use LTS` and the second started `When i hover over the short format ...`?

I am confused now what is not working on the tooltip for you?

Everytime I hover on a tooltip, it shows the date on the tooltip in complete correspondence with entered format. It even changes when I type? So what isn't working?

**Comment by Sopor** [comment] 2019-11-20 18:10
I didn't know if these was related to each other so i reported them as one.

The recent logins is now working but not the tooltip for the time in `Change Language and Theme`

**Comment by rostovtsev** [comment] 2019-11-20 18:27
Please explain what is not working on your side. The best is to make video-screencast, it's very easy.

**Comment by Sopor** [comment] 2019-11-21 11:00
You have screenshots at the top

**Comment by rostovtsev** [comment] 2019-11-21 11:06
But it just works for me? What browser and client OS?

**Comment by Sopor** [comment] 2019-11-22 22:00
Firefox 70.0.1 and Windows 10

**Comment by rostovtsev** [comment] 2019-11-22 22:15
I will test more tomorrow in my newly installed (physical) Windows 10.

By the way, unless you have updated the theme today, could you provide me the screenshot of your left navigation menu? Or if you did install update today, could you downgrade to the latest stable version of the theme and send me the screenshot of the navigation menu? I made a fix today, that improves icon's rendering in Windows.

**Comment by Sopor** [comment] 2019-11-22 22:16
It will show that `L` is default so i believe you need to change it first. Try adding `YYYY-MM-DD`, save it and go to the dashboard. Now open `Change Language and Theme` and without touching anything hover the mouse pointer over the `Shout format` window and it should show the default output example. If you now press the mouse pointer in the `Short format` window and move the mouse pointer away and back, it will now show that `L` is default but the output example has now been changed and it will show the date format `YYYY-MM-DD`.

**Comment by rostovtsev** [comment] 2019-11-22 22:18
@Sopor This is super explanations (report). I think I will be able to reproduce it now.

**Comment by Sopor** [comment] 2019-11-22 22:23
I'm running Authentic theme 19.40-RC1

**Comment by rostovtsev** [comment] 2019-11-22 22:26
It's fine, now take a screenshot of navigation menu and send it to me. Then update to the latest dev version (RC-3) and make another screenshot, and send it to me over email. Thanks.

**Comment by Sopor** [comment] 2019-11-22 22:30
Hmm, i can't see any difference between them when i change tabs between these two versions.

**Comment by rostovtsev** [comment] 2019-11-23 05:58
@Sopor There is a big difference! 🙂 You mustn't zoom in, though.

**Comment by rostovtsev** [comment] 2019-11-23 07:09
> It will show that L is default so i believe you need to change it first. Try adding YYYY-MM-DD, save it and go to the dashboard. Now open Change Language and Theme and ...

Fixed. Thanks for clear explanations.

**Comment by Sopor** [comment] 2019-11-23 12:19
> @Sopor There is a big difference! 🙂 You mustn't zoom in, though.

Zoom in?

**Comment by rostovtsev** [comment] 2019-11-23 13:10
Ya, like `Ctrl + +` or Ctrl + mouse wheel. In case it's standard scale, the icons looked torn a bit in Windows. It's improved now.
